version: "2"

services:
  faunadb:
    image: fauna-image
    container_name: faunadb

  tests:
    image: nodejs
    container_name: mytests
    depends_on:
      - faunadb
    command: bash -c "while ! $$(curl --output /dev/null --silent --fail --max-time 1 http://faunadb:8443/ping); do sleep 1; done"
