version: "2"

services:
  faunadb:
    image: fauna/faunadb
    container_name: faunadb

  tests:
    image: circleci/node:11.15
    container_name: mytests
    depends_on:
      - faunadb
    command: bash -c 'curl http://faunadb:8443/ping'
